"""empty message

Revision ID: 379e973ca44b
Revises: f954d04c4ecf
Create Date: 2024-03-08 14:46:26.893192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379e973ca44b'
down_revision = 'f954d04c4ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
